import { Suspense } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavigationEvents } from "@/common/components/navigation-events";
import { Navbar } from "@/common/ui/navbar";
import Providers from "../providers";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { lang: string };
}) {
  return (
    <html lang={lang} suppressHydrationWarning>
      <body className={inter.className}>
        <Providers>
          <Suspense fallback={null}>
            <Navbar />
            {children}
            <NavigationEvents />
          </Suspense>
        </Providers>
      </body>
    </html>
  );
}
